main: kreashenz.stuntguy3000.mcrp.MinecraftRP
name: MinecraftRP
version: 1.0
description: Meooow
softdepend: [Vault]
commands:
  ban:
    description: Ban a player
  broadcast:
    description: Broadcast a message
  kick:
    description: Kick a player
  msg:
    description: Private message a player
  reply:
    description: Reply to a private message
    aliases: [r]
  setspawn:
    description: Set the spawn location of the server
  spawn:
    description: Teleport to spawn
  tp:
    description: Teleport to a player
  tphere:
    description: Teleport a player to you
  tptoggle:
    description: Toggle whether to allow teleporting to you
  nick:
    description: Set a player's nickname.
  clear:
    description: Clear an inventory
  socialspy:
    description: Toggle socialspy
  speed:
    description: Set fly speed
  item:
    description: Spawn an item
  help:
    description: Send the help