main: kreashenz.stuntguy3000.mcrp.MinecraftRP
name: MinecraftRP
version: 1.0
description: Meooow
commands:
  ban:
    description: Ban a player
  kick:
    description: Kick a player
  msg:
    description: Private message a player
  reply:
    description: Reply to a private message
    aliases: [r]